# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlertMessage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlertMessage
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'mailcore2-ios'
end
